name: golang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v3.4.0
